### PR TITLE
[WIP] Script updates to Linux and MacOS

### PR DESCRIPTION
**Pull request by neomatrix369**
**Eventually these changes will be moved to `tdl-lord-of-runners`**

Updated record and upload bash script (Linux/MacOS) and also added a bunch of files to gitignore

We preserve the existing record_and_upload.sh script and phase it out slowly by introducing the new changes and using them.

### CODE REVIEW

**Comment by neomatrix369** [comment]
I have moved all the changed to https://github.com/julianghionoiu/tdl-lord-of-runners/pull/9 but this branch will help you test things out

**Comment by julianghionoiu** [comment]
Hey Mani,

We should not touch the tdl-runner-xxx repos. These are "production" repositories.
We can use tdl-lord-of-runners to package the recording with a runner project and into a tar file, then test using that.

**Comment by julianghionoiu** [comment]
I am going to close this one here.

**Comment by neomatrix369** [comment]
That wasn't the intention to merge into master, I was aware all along - I was using it to test my work and keeping a record, replica of the changes are already present on `tdl-lord-of-runners`

**Pull request closed without merging**
