### PR TITLE
Improve readme mvn and gradle steps

### PR DESCRIPTION
**Pull request by neomatrix369**
I have expanded on of the instructions again although I saw you made them compact, it has its advantages but the issue you want to avoid is people not knowing where to find the option.

For e.g. in the case of IntelliJ the Import project option is sort of obscured via another menu option, you can find it via Actions but then not everyone is familiar with it. It's more clear on the Welcome screen.

With steps for users, less it not good. Happy to make the sentences less verbose but not remove them totally

### CODE REVIEW

**Comment by neomatrix369** [comment]
This now works, updating the instructions for it under Eclipse:

image

**Comment by julianghionoiu** [comment]
> With steps for users, less it not good.

There is a tradeoff here. I want to keep the README short so that people that already know what they are doing (the majority) can just scroll to it but have enough information so that we point juniors in the right direction.

We do not want to give them step by step instructions but helpful pointers. This is a challenge after all, setting up is part of it.

**Review by julianghionoiu — APPROVED** [review]

**Comment by julianghionoiu** [comment]
I like the fact that we are pointing them in the right direction by specifying the links.

**Comment by neomatrix369** [comment]
https://github.com/julianghionoiu/tdl-runner-java/pull/16#issuecomment-430502319 That's fair point, its a challenge and we are giving them good hints and don't have to be literal about it

**Pull request merged**
